-- =========================
-- TASKS TABLE
-- =========================

CREATE TABLE tasks
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(255),
    title VARCHAR(255),
    date VARCHAR(255),
    priority VARCHAR(255)
);

-- Table: public.task_logs
CREATE TABLE IF NOT EXISTS task_logs
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    task_id bigint,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT task_logs_pkey PRIMARY KEY (id),
    CONSTRAINT task_logs_task_id_fkey FOREIGN KEY (task_id)
        REFERENCES public.tasks (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

-- =========================
-- TRIGGER FUNCTION (must exist first)
-- =========================

CREATE OR REPLACE FUNCTION insert_task_log()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO task_logs(task_id)
    VALUES (NEW.id);

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =========================
-- TRIGGER
-- =========================

CREATE TRIGGER after_task_insert
AFTER INSERT ON tasks
FOR EACH ROW
EXECUTE FUNCTION insert_task_log();

INSERT INTO public.tasks (title, description, date, priority)
VALUES (
    'Build Docker setup',
    'Create PostgreSQL + backend setup in Docker',
    '2026-06-07',
    'HIGH'
);
